name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Szoliman-Test
      id: szoliman-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 8
        setup-command: pip install bs4 cssutils
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SZOLIMAN-TEST_RESULTS: "${{steps.szoliman-test.outputs.result}}"
      with:
        runners: szoliman-test
